### ISSUE TITLE
希望添加一个开源协议的文件

### ISSUE THREAD

**Issue by jiangzhuo** [lizs/Pi#1]
我收录到了 https://github.com/jiangzhuo/OpenSourceGameServerEngine/blob/master/README.md 里
但是不知道用的什么开源协议

**Comment by lizs** [comment]
已添加（MIT）
谢谢。

在 2016-03-20 02:12:48，"Jiangzhuo" notifications@github.com 写道：

我收录到了 https://github.com/jiangzhuo/OpenSourceGameServerEngine/blob/master/README.md 里
但是不知道用的什么开源协议
